
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzQ3NDYwODc3LCJleHAiOjE3NDc0NjQ0NzcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.mvpM9I2vaoHfCevo3p2wm8AlIlx_gr9t9IB17c1zP00

{
  "firstName": "Muwanika",
  "lastName": "Jdiobe",
  "email": "muwanika@yahoo.com",
  "password": "Password123#"
}
