
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzQ3NjQ0NTI2LCJleHAiOjE3NDc2NDgxMjYsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.MlvUs_9go-aTXcj7mcx81oRMT2zz7laQAtXmTYJnDnk

{
  "firstName": "Muwanika",
  "lastName": "Jdiobe",
  "email": "muwanika@yahoo.com",
  "password": "Password123#"
}
