POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json


{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc0Nzk4NTI3NCwiZXhwIjoxNzQ4MDcxNjc0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.zuoUqndbG4pjyZhqSLju-1GuDFLmdLDPsgfih1P-XKo"
}